version: 1.0.{build}
environment:
  GITHUB_TOKEN:
    secure: 7PO9U+4orWRHDEbiEGwRmq3BTnssieZnkwX6562UAiogZ49idE2hVqQMhx2jXMca
branches:
  except:
  - master
image: Visual Studio 2013
clone_depth: 1
init:
- ps: >-
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    c:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P patchutils
install:
- cmd: >-
    cd "C:\Program Files (x86)\Microsoft SDKs\Windows"

    patch -p1 --binary < C:\projects\SoftEtherVPN\src\windows_sdk7.1A.patch
build_script:
- cmd: >-
    cd C:\projects\SoftEtherVPN\src

    cp ../appveyor/BuildAll.AppVeyor.VS2013.cmd BuildAll.AppVeyor.VS2013.cmd

    BuildAll.AppVeyor.VS2013.cmd
test: off
